### ISSUE TITLE
Upgrade to ES 2

### ISSUE THREAD

**Issue by rikatz** [codelibs/elasticsearch-solr-api#25]
So, ES 2 changed a lot of things on plugin schema. If it's possible (as I'm no Java developer, sorry :( ) would like to ask  to port this plugin to ES 2.

Thank you very much!

**Comment by marevol** [comment]
I'm not sure that users need this plugin on ES 2.x at the moment...
So, I'll work on ES 2.x support if this plugin gets over 100 stars.
Of course pull request is welcome.

**Comment by rikatz** [comment]
Trying to change some stuff, but there are a lot of changes on ES API from 1.7 to 2.x

Nevermind, closing this issue :) going to ask some Java developer on my company to help me with this, then going to do a PR ;)
